INSERT INTO `users` (`username`, `email`, `full_name`, `password`) VALUES
('rob','rob.stark@example.com','Robb Stark','pass123'),
('ned','ned.stark@example.com','Eddard Stark','pass123'),
('robert','robert.baratheon@example.com','Robert Baratheon','pass123'),
('jon_arryn','jon.arryn@westeros.example','Jon Arryn','pass123'),
('jon','jon.snow@example.com','Jon Snow','pass123'),
('daenerys','daenerys.targaryen@example.com','Daenerys Targaryen','pass123'),
('bran','bran.stark@example.com','Bran Stark','pass123'),
('sansa','sansa.stark@example.com','Sansa Stark','pass123'),
('cersei','cersei.lannister@example.com','Cersei Lannister','pass123'),
('jaime','jaime.lannister@example.com','Jaime Lannister','pass123'),
('samwell','samwell.tarly@example.com','Samwell Tarly','pass123'),
('brienne','brienne.tarth@example.com','Brienne of Tarth','pass123'),
('sandor','sandor.clegane@example.com','Sandor Clegane','pass123'),
('jorah','jorah.mormont@example.com','Jorah Mormont','pass123'),
('theon','theon.greyjoy@example.com','Theon Greyjoy','pass123'),
('yara','yara.greyjoy@example.com','Yara Greyjoy','pass123'),
('melisandre','melisandre@example.com','Melisandre','pass123'),
('varys','varys@example.com','Varys','pass123'),
('drogo','khal.drogo@example.com','Khal Drogo','pass123'),
('missandei','missandei@example.com','Missandei','pass123'),

('tywin','tywin.lannister@example.com','Tywin Lannister','pass123'),
('stannis','stannis.baratheon@example.com','Stannis Baratheon','pass123'),
('renly','renly.baratheon@example.com','Renly Baratheon','pass123'),
('joffrey','joffrey.baratheon@example.com','Joffrey Baratheon','pass123'),
('tyrion','tyrion.lannister@example.com','Tyrion Lannister','pass123'),
('catelyn','catelyn.tully@example.com','Catelyn Stark','pass123'),
('aegon','aegon.targaryen@example.com','Aegon Targaryen','pass123'),
('rickon','rickon.stark@example.com','Rickon Stark','pass123'),
('eddard','eddard.stark@example.com','Eddard Stark','pass123'),
('lyanna','lyanna.stark@example.com','Lyanna Stark','pass123'),
('marillion','marillion.tarth@example.com','Marillion Tarth','pass123'),
('doran','doran.martell@example.com','Doran Martell','pass123'),
('oberyn','oberyn.martell@example.com','Oberyn Martell','pass123'),
('aresa','aresa.martell@example.com','Aresa Martell','pass123'),
('aron','aron.greyjoy@example.com','Aron Greyjoy','pass123'),
('aeron','aeron.greyjoy@example.com','Aeron Greyjoy','pass123'),
('theon2','theon2.greyjoy@example.com','Theon Greyjoy II','pass123'),
('yara2','yara2.greyjoy@example.com','Yara Greyjoy II','pass123'),
('garlan','garlan.tyrell@example.com','Garlan Tyrell','pass123'),
('margaery','margaery.tyrell@example.com','Margaery Tyrell','pass123'),

('loras','loras.tyrell@example.com','Loras Tyrell','pass123'),
('meera','meera.reed@example.com','Meera Reed','pass123'),
('wylla','wylla.reed@example.com','Wylla Reed','pass123'),
('howland','howland.reed@example.com','Howland Reed','pass123'),
('roose','roose.bolton@example.com','Roose Bolton','pass123'),
('ramsey','ramsey.bolton@example.com','Ramsey Bolton','pass123'),
('walder','walder.frey@example.com','Walder Frey','pass123'),
('lothar','lothar.frey@example.com','Lothar Frey','pass123'),
('rhaegar','rhaegar.targaryen@example.com','Rhaegar Targaryen','pass123'),
('viserys','viserys.targaryen@example.com','Viserys Targaryen','pass123'),
('jon2','jon2.targaryen@example.com','Jon Targaryen II','pass123'),
('aegon2','aegon2.targaryen@example.com','Aegon Targaryen II','pass123'),
('salladhor','salladhor.saan@example.com','Salladhor Saan','pass123'),
('beric','beric.dondarrion@example.com','Beric Dondarrion','pass123'),
('thoros','thoros.dondarrion@example.com','Thoros Dondarrion','pass123'),
('davos','davos.seaworth@example.com','Davos Seaworth','pass123'),
('bronn','bronn@example.com','Bronn','pass123'),
('gilly','gilly@example.com','Gilly','pass123'),
('sam2','sam2.tarly@example.com','Samwell Tarly II','pass123'),
('shae','shae@example.com','Shae','pass123'),

('renly2','renly2.baratheon@example.com','Renly Baratheon II','pass123'),
('ellaria','ellaria.sand@example.com','Ellaria Sand','pass123'),
('tyene','tyene.sand@example.com','Tyene Sand','pass123'),
('obara','obara.sand@example.com','Obara Sand','pass123'),
('nymeria','nymeria.sand@example.com','Nymeria Sand','pass123'),
('jaqen','jaqen.hghar@example.com','Jaqen Hghar','pass123'),
('arya2','arya2.stark@example.com','Arya Stark II','pass123'),
('podrick','podrick.payne@example.com','Podrick Payne','pass123'),
('robin','robin.arryn@example.com','Robin Arryn','pass123'),
('lysa','lysa.arryn@example.com','Lysa Arryn','pass123'),
('marillion2','marillion2.tarth@example.com','Marillion Tarth II','pass123'),
('doran2','doran2.martell@example.com','Doran Martell II','pass123'),
('oberyn2','oberyn2.martell@example.com','Oberyn Martell II','pass123'),
('aresa2','aresa2.martell@example.com','Aresa Martell II','pass123'),
('aron2','aron2.greyjoy@example.com','Aron Greyjoy II','pass123'),
('aeron2','aeron2.greyjoy@example.com','Aeron Greyjoy II','pass123'),
('garlan2','garlan2.tyrell@example.com','Garlan Tyrell II','pass123'),
('margaery2','margaery2.tyrell@example.com','Margaery Tyrell II','pass123'),
('loras2','loras2.tyrell@example.com','Loras Tyrell II','pass123'),
('meera2','meera2.reed@example.com','Meera Reed II','pass123'),

('wylla2','wylla2.reed@example.com','Wylla Reed II','pass123'),
('howland2','howland2.reed@example.com','Howland Reed II','pass123'),
('roose2','roose2.bolton@example.com','Roose Bolton II','pass123'),
('ramsey2','ramsey2.bolton@example.com','Ramsey Bolton II','pass123'),
('walder2','walder2.frey@example.com','Walder Frey II','pass123'),
('lothar2','lothar2.frey@example.com','Lothar Frey II','pass123'),
('rhaegar2','rhaegar2.targaryen@example.com','Rhaegar Targaryen II','pass123'),
('viserys2','viserys2.targaryen@example.com','Viserys Targaryen II','pass123'),
('jon3','jon3.targaryen@example.com','Jon Targaryen III','pass123'),
('aegon3','aegon3.targaryen@example.com','Aegon Targaryen III','pass123'),
('salladhor2','salladhor2.saan@example.com','Salladhor Saan II','pass123'),
('beric2','beric2.dondarrion@example.com','Beric Dondarrion II','pass123'),
('thoros2','thoros2.dondarrion@example.com','Thoros Dondarrion II','pass123'),
('davos2','davos2.seaworth@example.com','Davos Seaworth II','pass123'),
('bronn2','bronn2@example.com','Bronn II','pass123'),
('gilly2','gilly2@example.com','Gilly II','pass123'),
('sam3','sam3.tarly@example.com','Samwell Tarly III','pass123'),
('shae2','shae2@example.com','Shae II','pass123'),
('ellaria2','ellaria2.sand@example.com','Ellaria Sand II','pass123'),
('arya','arya.stark@example.com','Arya Stark','pass123');

UPDATE `users` 
SET `password` = '$2a$12$rsH4xQP6BT.9f508L9Qiru2OtjvVfmYw16p/bD3VYHtacjH0Vyz5K';

INSERT INTO `user_roles` (`type`) VALUES ('ROOT'), ('ADMIN'), ('USER');

INSERT INTO `users_roles_map` (`user_id`, `role_id`)
SELECT `id`, 1 FROM `users` WHERE `id` = 1;

INSERT INTO `users_roles_map` (`user_id`, `role_id`)
SELECT `id`, 2 FROM `users` WHERE `id` BETWEEN 1 AND 4;

INSERT INTO `users_roles_map` (`user_id`, `role_id`)
SELECT `id`, 3 FROM `users`;